/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PairRouteImport } from './routes/pair'
import { Route as HomeRouteImport } from './routes/home'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as BannedRouteImport } from './routes/banned'
import { Route as AuthErrorRouteImport } from './routes/auth-error'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as RoomsRoomIdRouteImport } from './routes/rooms.$roomId'
import { Route as KioskDeviceIdRouteImport } from './routes/kiosk.$deviceId'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminRoomsRouteImport } from './routes/admin/rooms'
import { Route as AdminDevicesRouteImport } from './routes/admin/devices'
import { Route as AdminBookingsRouteImport } from './routes/admin/bookings'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PairRoute = PairRouteImport.update({
  id: '/pair',
  path: '/pair',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const BannedRoute = BannedRouteImport.update({
  id: '/banned',
  path: '/banned',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthErrorRoute = AuthErrorRouteImport.update({
  id: '/auth-error',
  path: '/auth-error',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const RoomsRoomIdRoute = RoomsRoomIdRouteImport.update({
  id: '/rooms/$roomId',
  path: '/rooms/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const KioskDeviceIdRoute = KioskDeviceIdRouteImport.update({
  id: '/kiosk/$deviceId',
  path: '/kiosk/$deviceId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRoomsRoute = AdminRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDevicesRoute = AdminDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth-error': typeof AuthErrorRoute
  '/banned': typeof BannedRoute
  '/bookings': typeof BookingsRoute
  '/home': typeof HomeRoute
  '/pair': typeof PairRoute
  '/profile': typeof ProfileRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/devices': typeof AdminDevicesRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/admin/users': typeof AdminUsersRoute
  '/kiosk/$deviceId': typeof KioskDeviceIdRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth-error': typeof AuthErrorRoute
  '/banned': typeof BannedRoute
  '/bookings': typeof BookingsRoute
  '/home': typeof HomeRoute
  '/pair': typeof PairRoute
  '/profile': typeof ProfileRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/devices': typeof AdminDevicesRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/admin/users': typeof AdminUsersRoute
  '/kiosk/$deviceId': typeof KioskDeviceIdRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth-error': typeof AuthErrorRoute
  '/banned': typeof BannedRoute
  '/bookings': typeof BookingsRoute
  '/home': typeof HomeRoute
  '/pair': typeof PairRoute
  '/profile': typeof ProfileRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/devices': typeof AdminDevicesRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/admin/users': typeof AdminUsersRoute
  '/kiosk/$deviceId': typeof KioskDeviceIdRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth-error'
    | '/banned'
    | '/bookings'
    | '/home'
    | '/pair'
    | '/profile'
    | '/admin/bookings'
    | '/admin/devices'
    | '/admin/rooms'
    | '/admin/users'
    | '/kiosk/$deviceId'
    | '/rooms/$roomId'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth-error'
    | '/banned'
    | '/bookings'
    | '/home'
    | '/pair'
    | '/profile'
    | '/admin/bookings'
    | '/admin/devices'
    | '/admin/rooms'
    | '/admin/users'
    | '/kiosk/$deviceId'
    | '/rooms/$roomId'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth-error'
    | '/banned'
    | '/bookings'
    | '/home'
    | '/pair'
    | '/profile'
    | '/admin/bookings'
    | '/admin/devices'
    | '/admin/rooms'
    | '/admin/users'
    | '/kiosk/$deviceId'
    | '/rooms/$roomId'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthErrorRoute: typeof AuthErrorRoute
  BannedRoute: typeof BannedRoute
  BookingsRoute: typeof BookingsRoute
  HomeRoute: typeof HomeRoute
  PairRoute: typeof PairRoute
  ProfileRoute: typeof ProfileRoute
  KioskDeviceIdRoute: typeof KioskDeviceIdRoute
  RoomsRoomIdRoute: typeof RoomsRoomIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pair': {
      id: '/pair'
      path: '/pair'
      fullPath: '/pair'
      preLoaderRoute: typeof PairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banned': {
      id: '/banned'
      path: '/banned'
      fullPath: '/banned'
      preLoaderRoute: typeof BannedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-error': {
      id: '/auth-error'
      path: '/auth-error'
      fullPath: '/auth-error'
      preLoaderRoute: typeof AuthErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/rooms/$roomId': {
      id: '/rooms/$roomId'
      path: '/rooms/$roomId'
      fullPath: '/rooms/$roomId'
      preLoaderRoute: typeof RoomsRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kiosk/$deviceId': {
      id: '/kiosk/$deviceId'
      path: '/kiosk/$deviceId'
      fullPath: '/kiosk/$deviceId'
      preLoaderRoute: typeof KioskDeviceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rooms': {
      id: '/admin/rooms'
      path: '/rooms'
      fullPath: '/admin/rooms'
      preLoaderRoute: typeof AdminRoomsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/devices': {
      id: '/admin/devices'
      path: '/devices'
      fullPath: '/admin/devices'
      preLoaderRoute: typeof AdminDevicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminDevicesRoute: typeof AdminDevicesRoute
  AdminRoomsRoute: typeof AdminRoomsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBookingsRoute: AdminBookingsRoute,
  AdminDevicesRoute: AdminDevicesRoute,
  AdminRoomsRoute: AdminRoomsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthErrorRoute: AuthErrorRoute,
  BannedRoute: BannedRoute,
  BookingsRoute: BookingsRoute,
  HomeRoute: HomeRoute,
  PairRoute: PairRoute,
  ProfileRoute: ProfileRoute,
  KioskDeviceIdRoute: KioskDeviceIdRoute,
  RoomsRoomIdRoute: RoomsRoomIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
