# fly.toml app configuration file generated for room-booking-api on 2026-06-21T20:30:28+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'room-booking-api'
primary_region = 'sin'

[build]
  dockerfile = 'Dockerfile'

[deploy]
  release_command = "bun run migrate"

[env]
  BUN_ENV = 'production'
  NODE_ENV = 'production'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = 'requests'
    soft_limit = 20
    hard_limit = 25

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/api/health'
    protocol = 'http'

[[vm]]
  memory = '1gb'
  cpus = 1
